title: Richard Krajnyik project portfolio
description: > # this means to ignore newlines until "baseurl:"

  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://powerof.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Richard Krajnyik # add your name
author-img: richard-krajnyik.jpg # add your photo
about-author: I am a Software Engineer with close to 10 years background testing Desktop, Web and Mobile applications. You can check out my various projects in the pinned post on the right side! If you'd like to get in touch, don't hesitate to reach out on the contacts below.  # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: PowerOf # add your Github handle
social-linkedin: richard-krajnyik-65078572 # add your Linkedin handle
social-email: richard.krajnyik@gmail.com # add your Email address

# Disqus
discus-identifier: richrdkrajnyik # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
